### ISSUE TITLE
Standalone client

### ISSUE THREAD

**Issue by mrueg** [mopidy/mopidy-mpris#16]
As a user I'd like to run mopidy on a remote server and communicate with it using mpris. 
It would be great to have a standalone version of mopidy-mpris, that runs on the client and connects to a mopidy-mpris-socket plugin via tcp / unix sockets.

This also would avoid patching mpris clients to use the system-wide dbus for communication with mopidy, if the mopidy server is run by another user.

**Comment by jodal** [comment]
I like the idea, but I'm probably not going to spend any time on this in the near future.

**Comment by dz0ny** [comment]
or just  connect to existing mopidy websocket.

**Comment by jodal** [comment]
I can imagine two different solutions here:

1. A generic MPRIS or D-Bus proxy that lets you reexport the MPRIS interface on the D-Bus bus of another system.
2. Use the [Mopidy HTTP RPC or WebSocket APIs](https://docs.mopidy.com/en/latest/api/http/).

A third solution as a part of Mopidy-MPRIS is out of scope for this project, so I'm closing this.
