### ISSUE TITLE
Can't connect after upgrading to Mopidy 2.0.1

### ISSUE THREAD

**Issue by m0ngr31** [mopidy/mopidy-mpris#18]
Everything has been working fine, and then I upgraded to Mopidy 2.0.1 and now it won't connect. I get this error:

`WARNING  MPRIS frontend setup failed (org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-f2aNzfac4u: Connection refused)`

Anything I can try to get this working?

**Comment by kgizdov** [comment]
I'm getting a similar error, but not exactly

`MPRIS frontend setup failed (org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead)`

**Comment by kingosticks** [comment]
@kgizdov This looks different, more likely to be a problem with your system configuration, I'd be surprised to hear that this started after just upgrading Mopidy.

Please start your own thread. You might find http://discuss.mopidy.com a better place to post than this bug tracker.

**Comment by kgizdov** [comment]
Sure, I'll post there. But `DBUS_SESSION_BUS_ADDRESS` is correctly set and passed to the service. I have no custom config on the system.

**Comment by jodal** [comment]
As the original question is 2.5 years old and still unanswered, I'm closing this.

If anyone has a similar issue, please ask for help at https://discourse.mopidy.com.

If anyone has configuration tips that should be added to the Mopidy-MPRIS docs, please contribute in #14 or #15.
