### ISSUE TITLE
MPRIS frontend setup failed ...

### ISSUE THREAD

**Issue by bernd-wechner** [mopidy/mopidy-mpris#19]
I am running mopidy on a Mint system as a service using pulseaudio and it's working fine. Early days, just experimenting, but am listening to music as I write. Alas MPRIS was failing on hte lack of a  $DISPLAY variable but the README here explained that and so I changed it from the session to the system bus and restarted. Only to find a new issue:

`2017-06-11 16:22:45,730 WARNING [15062:MprisFrontend-11] mopidy_mpris.frontend: MPRIS frontend setup failed (org.freedesktop.DBus.Error.AccessDenied: Connection ":1.2293" is not allowed to own the service "org.mpris.MediaPlayer2.mopidy" due to security policies in the configuration file)`

Alas, that one is not covered in the README ;-). Which configuration file? Looks fixable but I admit to low skills in this area and gratitude for any pointers and perhaps the learning belongs in the README. I kind of like the MPRIS support on the HTPC I'm using.

**Comment by gerroon** [comment]
I am having the same issue. I set  the mpris system

**Comment by txomon** [comment]
Check your dbus configuration, as this error seems to be related to a configuration problem. https://stackoverflow.com/questions/4560877/dbus-bus-request-name-connections-are-not-allowed-to-own-the-service

**Comment by jodal** [comment]
1.5y since question, 0.5y since potential answer, then silence. Closing.

If you have anything to add, we're tracking how to document D-Bus permission setup in #14.
