### ISSUE TITLE
 MPRIS frontend setup failed (org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11)

### ISSUE THREAD

**Issue by gerroon** [mopidy/mopidy-mpris#20]
Hi

" MPRIS frontend setup failed (org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11)"

 I saw the message above in the log and I have no idea why that is the case. After googling abit I tried using "system" for dbus thingy then this is what I got

WARNING  MPRIS frontend setup failed (org.freedesktop.DBus.Error.AccessDenied: Connection ":1.165" is not allowed to own th[54/278]
e "org.mpris.MediaPlayer2.mopidy" due to security policies in the configuration file)

Catch 22?

I am using mopid 2.1.0 on Debian Testing x64 with systemd.

**Comment by jodal** [comment]
I don't an answer for you right away (almost a year later), but we're tracking the addition of docs for your first issue in #15 and your second issue in #14. Please add to those issues if you made any progress on this.
