### ISSUE TITLE
Wrong types for properties

### ISSUE THREAD

**Issue by phako** [mopidy/mopidy-mpris#22]
(rygel:6812): GLib-GIO-WARNING **: 19:50:19.607: Received property Position with type i does not match expected type x in the expected interface

(rygel:6812): GLib-GIO-WARNING **: 19:50:19.608: Received property Metadata with type a{ss} does not match expected type a{sv} in the expected interface

See https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Position and https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Metadata

**Comment by phako** [comment]
This might actually be fixed, I seem to have a rather old version

**Comment by jodal** [comment]
I'd guess it has changed in the master branch which rewrites much of Mopidy-MPRIS.

As to why I haven't released 2.0.0, I don't remember. If you give it a spin and it works for you, I can get a release out.

**Comment by jodal** [comment]
Mopidy-MPRIS 2.0.0 has now been released, in case you are interested in verifying that this has been fixed.

**Comment by phako** [comment]
I finally managed to try it. There's something wrong with your entry-point. It should be  /org/mpris/MediaPlayer2

https://specifications.freedesktop.org/mpris-spec/latest/#Entry-point

**Comment by phako** [comment]
Ah sorry, I was on my fork, not your repository

**Comment by jodal** [comment]
So all good? :-)

**Comment by phako** [comment]
Yup :)
