### ISSUE TITLE
Album art not showing up

### ISSUE THREAD

**Issue by ReekyMarko** [mopidy/mopidy-mpris#25]
I was using MPD and mpDris2 until today when I decided to switch to Mopidy. Previously I had album art show up on mpris clients, but not with this new combination. Is this feature not implemented or am I missing something in my setup? My album art is inside the album directory as cover.jpg.

**Comment by jodal** [comment]
Mopidy-MPRIS supports cover art, but I don't think Mopidy-Local exposes cover art from disk by default. I think https://github.com/tkem/mopidy-local-images is a solution.

That said, please use https://discourse.mopidy.com for help with using Mopidy in the future. We try to reserve GitHub Issues for bugs.

**Comment by ReekyMarko** [comment]
Ok thanks for your input. And sorry for cluttering your issue tracker :innocent:
