### ISSUE TITLE
getting error while trying to control mopidy using playerctl if I wanna play the previous song

### ISSUE THREAD

**Issue by eyadsibai** [mopidy/mopidy-mpris#29]
```
➜  ~ playerctl -p mopidy previous
No player could handle this command
➜  ~ playerctl -p mopidy next    
➜  ~ 
```

I am able to play the next track but not the previous one 
pausing/ playing works too

**Comment by jodal** [comment]
I tried reproducing with Mopidy 3.0.1, Mopidy-MPRIS 3.0.1, and playerctl 2.0.2:

- When playing regularly, `previous` skipped back to the previous track.
- When playing in "random" mode (`playerctl shuffle on`) or "single" mode (`playerctl loop track`), `previous` did not, as expected, have any effect. I did not get an error.

Do you have any more details to provide, making this easier for me to reproduce?

**Comment by eyadsibai** [comment]
I am using:
- playerctl 2.1.1
- mopidy-mpris 3.0.1
- mopidy 3.0.1

Please let me know what further information is needed and happy to share.

**Comment by eyadsibai** [comment]
Actually today it started working again! 

will close this. I have no clue what was the reason but I believe I restarted my machine recently.
