### ISSUE TITLE
MPRIS does not work on Raspbian / Raspberry Pi

### ISSUE THREAD

**Issue by olejon** [mopidy/mopidy-mpris#3]
Clean installation of the latest version of Raspbian. Installed Mopidy with Spotify extension, working as expected.

The MPRIS extension does not work. When Mopidy is started, I get this:

```
MPRIS server connected to D-Bus
MPRIS frontend setup failed ('module' object has no attribute 'Server')
```

Any ideas?

PS: It works as expected on my Ubuntu 12.04 laptop.

**Comment by jodal** [comment]
I'm closing this bug as it doesn't relate to a single issue any more:

- The original issue of @olejon resolved itself.
- The need for a dependency on python-gtk2 hasn't been mentioned in ages, so I suspect some other package in the dependency chain has fixed this.
- The `DISPLAY` check mentioned in my 2014-03-20 comment to @robbiet480 was removed in a pull request merged today.
- As for @tmerten's last comment half a year ago, we now have an `mpris/bus_type` config value that can be used to test Mopidy-MPRIS connected to the system bus and what clients care about that bus. The results of that may lead to a recommended headless setup for Mopidy-MPRIS+Rygel. Feel free to open a new issue to track that effort.
