### ISSUE TITLE
"An X11 $DISPLAY is needed to use D-Bus" when running as system daemon

### ISSUE THREAD

**Issue by totokaka** [mopidy/mopidy-mpris#9]
I am running mopidy as a system daemon in it's own separate user. I think this is a good way to run i for my purposes, but I would like to be able to control mopidy with my keyboard's media keys when I am logged in on the computer running mopidy.

I am getting this error when I try to run mopidy with mpris:

    INFO     Disabled extension mpris: An X11 $DISPLAY is needed to use D-Bus

I do not know how dbus works beside being a message bus, but as far as I understand there is a system wide bus in addition to the user specific bus. I have a feeling the MPRIS media events are only broadcast on the user bus, in which case this might be impossible. Either way, I'd like to somehow control mopidy through the media keys on my keyboard.

**Comment by jodal** [comment]
I don't know the details/differences of MPRIS on the session bus vs the system bus myself.

As an experiment, you can try changing `SessionBus` to `SystemBus` on https://github.com/mopidy/mopidy-mpris/blob/master/mopidy_mpris/objects.py#L83, and see if you'll be able to control it from your own user through the system bus.

**Comment by totokaka** [comment]
After doing that change and also commenting out the environment variable check on https://github.com/mopidy/mopidy-mpris/blob/master/mopidy_mpris/__init__.py#L27-L29 mopidy-mpris gave me this error:

    WARNING  MPRIS frontend setup failed (org.freedesktop.DBus.Error.AccessDenied: Connection ":1.83" is not allowed to own the service "org.mpris.MediaPlayer2.mopidy" due to security policies in the configuration file)

I will see if I can find a way to solve that.

**Comment by totokaka** [comment]
The AccessDenied error was easily avoidable by configuring a dbus policy for mopidy.
Here is what I put in my `/etc/dbus-1/system-local.config`:

    <!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
     "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
    <busconfig>
        <policy user="mopidy">
            <allow own="org.mpris.MediaPlayer2.mopidy"/>
        </policy>
        <policy user="root">
            <allow send_type="method_call"/>
        </policy>
    </busconfig>

Here I first allow the mopidy user to register itself as the owner of `org.mpris.MediaPlayer2.mopidy`, then I allow root to call methods. The root policy was needed for testing.

When I had those policies, I was able to control mopidy through the system bus, for example:

    sudo dbus-send --system --print-reply --dest=org.mpris.MediaPlayer2.mopidy /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri string:spotify:track:6JfGHYsw9LVH5FJMCh66Um

Media keys does not work, neither does connecting to mopidy through the session bus.

**Comment by MurzNN** [comment]
@totokaka, can you describe how I can configure work media buttons via normal user (not root)?
